sudo: required
services:
  - docker

before_install:
  - docker build -t nishantbhosale/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true nishantbhosale/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-ap-south-1-677413250510"
  bucket_path: "docker-react"
  on:
    branch: main
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
