sudo: required
services: 
  - docker

before_install:
  - docker build -t nishantbhosale/docker-react -f Dockerfile.dev .

script:
  - docker run nishantbhosale/docker-react npm run test -- --coverage 